feat: Add twine dependency and enhance pypi-publish workflow with version logging and default input

diff --git a/.github/workflows/pypi-publish.yml b/.github/workflows/pypi-publish.yml
--- a/.github/workflows/pypi-publish.yml
+++ b/.github/workflows/pypi-publish.yml
@@ -7,6 +7,7 @@ on:
         description: "Use version from pyproject.toml"
         required: true
         type: boolean
+        default: true
       release_version:
         description: "Or tag name for the release"
         required: false
@@ -33,8 +34,14 @@ jobs:
         run: |
           if [ "${{ github.event.inputs.from_pyproject }}" = true ]; then
             release_version=$(poetry version -s)
+            echo "Using version from pyproject.toml: $release_version"
           else
+            if [ -z "${{ github.event.inputs.release_version }}" ]; then
+              echo "Error: No release version provided and not using pyproject.toml version."
+              exit 1
+            fi
             release_version=${{ github.event.inputs.release_version }}
+            echo "Using provided release version: $release_version"
           fi
           echo "release_version=$release_version" >> $GITHUB_OUTPUT
 
@@ -42,38 +49,6 @@ jobs:
         shell: bash
         run: |
           poetry version ${{ steps.determine_version.outputs.release_version }}
-
-      - name: Check if version needs to be committed
-        id: check_version
-        shell: bash
-        run: |
-          current_version=$(poetry version -s)
-          release_version=${{ steps.determine_version.outputs.release_version }}
-          if [ "$current_version" != "$release_version" ]; then
-            poetry version ${{ steps.determine_version.outputs.release_version }} # Update version here directly
-            echo "version_changed=true" >> $GITHUB_OUTPUT
-          else
-            echo "version_changed=false" >> $GITHUB_OUTPUT
-          fi
-
-      - name: Build i18n files
-        shell: bash
-        run: |
-          pybabel compile -d sprinkles/src/locale
-
-      - name: Commit version and i18n changes
-        shell: bash
-        if: steps.check_version.outputs.version_changed == 'true'
-        env:
-          version_changed: ${{ steps.check_version.outputs.version_changed }}
-        run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
-          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}
-          git add pyproject.toml
-          git add sprinkles/src/locale
-          git commit -m "chore: Update version to ${{ steps.determine_version.outputs.release_version }} and update i18n files"
-          git push origin HEAD:${{ github.ref }}
 
       - name: Build
         shell: bash
@@ -92,7 +67,9 @@ jobs:
         uses: softprops/action-gh-release@v1
         with:
           files: dist/*
-          tag_name: ${{ steps.determine_version.outputs.release_version }}
+          tag_name: v${{ steps.determine_version.outputs.release_version }}
           token: ${{ secrets.GITHUB_TOKEN }}
           generate_release_notes: true
-          prerelease: true
+          prerelease: false
+          name:
+            "Release v${{ steps.determine_version.outputs.release_version }}"
